foreground            #e1e2e9
background            #111318
selection_foreground  #d9e3f8
selection_background  #3d4758
url_color             #a6c8ff

cursor                #a6c8ff
cursor_text_color     #02315f

# black
color0   #43474e
color8   #8d9199

# red
color1   #ffb4ab
color9   #ffb4ab

# green
color2   #a6c8ff
color10  #d5e3ff

# yellow
color3   #bdc7dc
color11  #d9e3f8

# blue
color4   #dabde2
color12  #f8d8ff

# magenta
color5   #3d5f90
color13  #93000a

# cyan
color6   #234776
color14  #3d4758

# white
color7   #c4c6cf
color15  #e1e2e9
