general {
    lock_cmd         = qs ipc call cherry-lock trigger
    before_sleep_cmd = qs ipc call cherry-lock trigger
    after_sleep_cmd  = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
    timeout = 300
    on-timeout = qs ipc call cherry-lock trigger
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}