#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  🎨 System Theme Switcher
#  Applies themes globally: Waybar · Rofi · Kitty · Dunst · GTK
# ═══════════════════════════════════════════════════════════════

THEMES_DIR="$HOME/.config/waybar/styles/themes"
CURRENT_SYMLINK="$THEMES_DIR/current.css"
KITTY_CONF="$HOME/.config/kitty/theme.conf"
ROFI_COLORS="$HOME/.config/rofi/colors.rasi"
DUNST_CONF="$HOME/.config/dunst/dunstrc"

# ── Ordered theme list for Rofi display ──────────────────────────────────────
# Format: "Display Name|filename.css"
ORDERED_THEMES=(
    "󰄛 Catppuccin Mocha|catppuccin-mocha.css"
    "󰄛 Catppuccin Frappe|catppuccin-frappe.css"
    "󰄛 Catppuccin Macchiato|catppuccin-macchiato.css"
    "󰄛 Catppuccin Latte (Light)|catppuccin-latte.css"
    "󰂵 Tokyo Night|tokyo-night.css"
    "󰨛 Nord|nord.css"
    "󰌁 Gruvbox|gruvbox.css"
    "󰠖 Rose Piné|rose-pine.css"
    "󰌔 Dracula|dracula.css"
    "󰩈 Cyberpunk|cyberpunk.css"
    "󰏘 All White (Light)|all-white.css"
)

# ── Theme color palette definitions ─────────────────────────────────────────
# Sets theme variables directly in the caller's scope via global vars
set_theme_vars() {
    local theme="$1"
    case "$theme" in
        all-white.css)
            THEME_BG="#ffffff"; THEME_FG="#0f172a"; THEME_ACCENT="#0891b2"
            THEME_BORDER="#14532d"; THEME_INPUT_BG="#f1f5f9"; THEME_LIGHT=1
            ;;
        catppuccin-latte.css)
            THEME_BG="#eff1f5"; THEME_FG="#4c4f69"; THEME_ACCENT="#8839ef"
            THEME_BORDER="#8839ef"; THEME_INPUT_BG="#e6e9ef"; THEME_LIGHT=1
            ;;
        tokyo-night.css)
            THEME_BG="#1a1b26"; THEME_FG="#c0caf5"; THEME_ACCENT="#7aa2f7"
            THEME_BORDER="#7aa2f7"; THEME_INPUT_BG="#24283b"; THEME_LIGHT=0
            ;;
        nord.css)
            THEME_BG="#2e3440"; THEME_FG="#d8dee9"; THEME_ACCENT="#88c0d0"
            THEME_BORDER="#88c0d0"; THEME_INPUT_BG="#434c5e"; THEME_LIGHT=0
            ;;
        gruvbox.css)
            THEME_BG="#282828"; THEME_FG="#fbf1c7"; THEME_ACCENT="#fabd2f"
            THEME_BORDER="#fabd2f"; THEME_INPUT_BG="#504945"; THEME_LIGHT=0
            ;;
        rose-pine.css)
            THEME_BG="#191724"; THEME_FG="#e0def4"; THEME_ACCENT="#ebbcba"
            THEME_BORDER="#ebbcba"; THEME_INPUT_BG="#26233a"; THEME_LIGHT=0
            ;;
        dracula.css)
            THEME_BG="#282a36"; THEME_FG="#f8f8f2"; THEME_ACCENT="#bd93f9"
            THEME_BORDER="#bd93f9"; THEME_INPUT_BG="#44475a"; THEME_LIGHT=0
            ;;
        cyberpunk.css)
            THEME_BG="#0d0f18"; THEME_FG="#e0f7fa"; THEME_ACCENT="#ff007f"
            THEME_BORDER="#00f0ff"; THEME_INPUT_BG="#212642"; THEME_LIGHT=0
            ;;
        catppuccin-macchiato.css)
            THEME_BG="#24273a"; THEME_FG="#cad3f5"; THEME_ACCENT="#c6a0f6"
            THEME_BORDER="#c6a0f6"; THEME_INPUT_BG="#363a4f"; THEME_LIGHT=0
            ;;
        catppuccin-frappe.css)
            THEME_BG="#303446"; THEME_FG="#c6d0f5"; THEME_ACCENT="#ca9ee6"
            THEME_BORDER="#ca9ee6"; THEME_INPUT_BG="#414559"; THEME_LIGHT=0
            ;;
        catppuccin-mocha.css|*)
            THEME_BG="#1e1e2e"; THEME_FG="#cdd6f4"; THEME_ACCENT="#cba6f7"
            THEME_BORDER="#cba6f7"; THEME_INPUT_BG="#313244"; THEME_LIGHT=0
            ;;
    esac
}

# ── Apply all system-wide color changes ─────────────────────────────────────
apply_system_colors() {
    local theme="$1"

    # Set THEME_* global variables for this theme
    set_theme_vars "$theme"
    local bg="$THEME_BG" fg="$THEME_FG" accent="$THEME_ACCENT"
    local border="$THEME_BORDER" input_bg="$THEME_INPUT_BG" is_light="$THEME_LIGHT"

    # ── 1. Rofi Colors ────────────────────────────────────────────────────────
    mkdir -p "$(dirname "$ROFI_COLORS")"
    cat > "$ROFI_COLORS" << ROFI_EOF
/* Auto-generated by theme-switcher.sh  -  do not edit */
* {
    background:   $bg;
    foreground:   $fg;
    selected:     $accent;
    border-col:   $border;
    input-bg:     $input_bg;
}
ROFI_EOF

    # ── 2. Kitty Terminal ─────────────────────────────────────────────────────
    mkdir -p "$(dirname "$KITTY_CONF")"
    if [[ "$is_light" == "1" ]]; then
        cat > "$KITTY_CONF" << KITTY_EOF
# Auto-generated by theme-switcher.sh  -  do not edit
background $bg
foreground $fg
cursor $accent
selection_background $accent
selection_foreground $bg
active_border_color $accent
inactive_border_color $border

# High-contrast ANSI 16 palette for light mode (Red, Green, Orange, Aqua, Blue, Purple)
color0  #0f172a
color1  #dc2626
color2  #15803d
color3  #c2410c
color4  #1d4ed8
color5  #7e22ce
color6  #0891b2
color7  #334155
color8  #64748b
color9  #b91c1c
color10 #166534
color11 #ea580c
color12 #2563eb
color13 #9333ea
color14 #0e7490
color15 #0f172a
KITTY_EOF
    else
        cat > "$KITTY_CONF" << KITTY_EOF
# Auto-generated by theme-switcher.sh  -  do not edit
background $bg
foreground $fg
cursor $accent
selection_background $accent
selection_foreground $bg
active_border_color $accent
inactive_border_color $border

# Vibrant ANSI 16 palette for dark mode
color0  #45475a
color1  #f38ba8
color2  #a6e3a1
color3  #fab387
color4  #89b4fa
color5  #cba6f7
color6  #94e2d5
color7  #bac2de
color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #a6adc8
KITTY_EOF
    fi
    # Signal all kitty instances to reload
    pkill -SIGUSR1 kitty 2>/dev/null || true

    # ── 3. Hyprland Window Borders ────────────────────────────────────────────
    hyprctl keyword general:col.active_border "0xff${accent#'#'}" >/dev/null 2>&1 || true

    # ── 4. Dunst Notifications ────────────────────────────────────────────────
    if [ -f "$DUNST_CONF" ]; then
        sed -i "s/frame_color = .*/frame_color = \"$accent\"/" "$DUNST_CONF"
        sed -i "s/background = .*/background = \"$bg\"/" "$DUNST_CONF"
        sed -i "s/foreground = .*/foreground = \"$fg\"/" "$DUNST_CONF"
        killall dunst 2>/dev/null || true
        setsid dunst &>/dev/null &
    fi

    # ── 5. GTK Light/Dark Mode + Cursor Theme ────────────────────────────────
    if [[ "$is_light" == "1" ]]; then
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' 2>/dev/null || true
        gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita' 2>/dev/null || true
        gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita' 2>/dev/null || true
        hyprctl setcursor Adwaita 24 2>/dev/null || true
    else
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null || true
        gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' 2>/dev/null || true
        gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice' 2>/dev/null || true
        hyprctl setcursor Bibata-Modern-Ice 24 2>/dev/null || true
    fi

    # ── 6. Set XDG color scheme for apps that read it ────────────────────────
    if [[ "$is_light" == "1" ]]; then
        mkdir -p "$HOME/.config"
        echo "prefer-light" > "$HOME/.config/color-scheme"
    else
        mkdir -p "$HOME/.config"
        echo "prefer-dark" > "$HOME/.config/color-scheme"
    fi

    # ── 7. Generate AGS Theme Colors ──────────────────────────────────────────
    mkdir -p "$HOME/.config/ags"
    cat > "$HOME/.config/ags/theme.scss" << AGS_EOF
// Auto-generated by theme-switcher.sh
\$theme-bg: ${bg};
\$theme-fg: ${fg};
\$theme-accent: ${accent};
\$theme-border: ${border};
\$theme-input-bg: ${input_bg};
\$theme-is-light: ${is_light};
AGS_EOF
}

# ── Reload AGS styles ────────────────────────────────────────────────────────
reload_waybar() {
    # Recompile CSS live and notify AGS to apply instantly without dropping windows
    sass "$HOME/.config/ags/style.scss" /tmp/ags-style.css 2>/dev/null || true
    ags request "reload-css" 2>/dev/null || true
}

# ── Apply a theme by filename ─────────────────────────────────────────────────
set_theme() {
    local theme_file="$1"
    if [ -f "$THEMES_DIR/$theme_file" ]; then
        # 1. Update current.css symlink
        ln -sf "$THEMES_DIR/$theme_file" "$CURRENT_SYMLINK"

        # 2. Apply system-wide colors
        apply_system_colors "$theme_file"

        # 3. Reload Waybar styles
        reload_waybar

        # 4. Save last-applied theme
        echo "$theme_file" > "$HOME/.config/current-theme"

        # 5. Notify user
        local name="${theme_file%.css}"
        notify-send "🎨 Theme Changed" "Now using: $name" \
            --icon=preferences-desktop-theme \
            --urgency=low 2>/dev/null || true
    else
        notify-send "⚠️ Theme Switcher" "Theme file not found: $theme_file" \
            --urgency=normal 2>/dev/null || true
    fi
}

# ── Show Rofi theme picker ────────────────────────────────────────────────────
show_menu() {
    # Build sorted display list
    local display_list=""
    for entry in "${ORDERED_THEMES[@]}"; do
        local name="${entry%%|*}"
        display_list+="$name\n"
    done

    # Get current theme for indicator
    local current_file=""
    if [ -L "$CURRENT_SYMLINK" ]; then
        current_file=$(basename "$(readlink "$CURRENT_SYMLINK")")
    fi

    local choice
    choice=$(printf "%b" "$display_list" | rofi \
        -dmenu \
        -p "󰏘  Theme" \
        -theme "$HOME/.config/rofi/theme-picker.rasi" \
        -i \
        -no-custom \
        -format s \
        -selected-row 0)

    if [ -z "$choice" ]; then return; fi

    # Match choice to theme file
    for entry in "${ORDERED_THEMES[@]}"; do
        local name="${entry%%|*}"
        local file="${entry##*|}"
        if [[ "$name" == "$choice" ]]; then
            set_theme "$file"
            break
        fi
    done
}

# ── Cycle to next theme ───────────────────────────────────────────────────────
cycle_next() {
    local files=()
    for entry in "${ORDERED_THEMES[@]}"; do
        files+=("${entry##*|}")
    done

    local current="${files[0]}"
    if [ -L "$CURRENT_SYMLINK" ]; then
        current=$(basename "$(readlink "$CURRENT_SYMLINK")")
    fi

    local next="${files[0]}"
    for i in "${!files[@]}"; do
        if [[ "${files[$i]}" == "$current" ]]; then
            local next_idx=$(( (i + 1) % ${#files[@]} ))
            next="${files[$next_idx]}"
            break
        fi
    done
    set_theme "$next"
}

# ── Cycle to previous theme ───────────────────────────────────────────────────
cycle_prev() {
    local files=()
    for entry in "${ORDERED_THEMES[@]}"; do
        files+=("${entry##*|}")
    done

    local current="${files[0]}"
    if [ -L "$CURRENT_SYMLINK" ]; then
        current=$(basename "$(readlink "$CURRENT_SYMLINK")")
    fi

    local prev="${files[${#files[@]}-1]}"
    for i in "${!files[@]}"; do
        if [[ "${files[$i]}" == "$current" ]]; then
            local prev_idx=$(( (i - 1 + ${#files[@]}) % ${#files[@]} ))
            prev="${files[$prev_idx]}"
            break
        fi
    done
    set_theme "$prev"
}

# ── Entry point ───────────────────────────────────────────────────────────────
case "$1" in
    set)
        set_theme "$2"
        ;;
    next)
        cycle_next
        ;;
    prev)
        cycle_prev
        ;;
    menu|"")
        show_menu
        ;;
    *)
        echo "Usage: $0 [menu|set <theme.css>|next|prev]"
        exit 1
        ;;
esac
